name: Prueba enlaces test cafe
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Install vitest
        run: npm install vitest --save-dev

      - name: Run tests
        run: npm test ./tests/test_enlaces.js
